version: '3'
services:


    # генерирует тестовый лог для проверки работоспособности системы
    log-generator:
        image: vadimivlev/log-generator:latest
        container_name: log-generator-dev
        restart: unless-stopped
        environment: 
            # максимальная задержка добавления записей в лог
            - MAX_DELAY=5000
            # максимальное количество добавленных записей лога перед ротацией
            - MAX_RECORDS=10
            # имя файла лога внутри директории назначенной в параметре volumes:
            - LOG_FILE=logrus.log
            # адрес elasticsearch для прямой записи логов
            - ELASTIC_URL=http://elk:9200
            # хост elasticsearch для прямой записи логов
            - ELASTIC_HOST=elk
        volumes: 
            - ./logs:/app/logs

networks:
    default:
        external:
            name: auth_proxy_network    